### ISSUE TITLE
The page is loading too slowly 

### ISSUE THREAD

**Issue by GuiWukai** [chimano/SOEN341_SA2#51]
We would like to improve the loading speed of the website

Story points: 2
Priority: A
Risk: Low

**Comment by alireza260** [comment]
I think that the issue might be because the Home Page is a bit too heavy (with all the CSS files that need to be loaded for the components). Maybe moving the reply button from the Home Page to another page exclusively for the questions could be a solution. Also, maybe we should reduce the number of displayed top questions.

**Comment by dobrovv** [comment]
Check it in the developer tools ->network with disabled cache
Looks like a file from https://at.alicdn.com/t/font_148784_dky7e838xq4obt9.woff is loading for 2-9 seconds
